#![allow(
    non_camel_case_types,
    non_snake_case,
    dead_code,
    non_upper_case_globals
)]

// Bindings generated by bindgen from wrapper.h (re_types.h + re_dbg.h +
// re.h + baresip.h). The build.rs writes them to OUT_DIR/bindings.rs.
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// ── Type aliases for ergonomic Rust naming ──────────────────────────────────
// bindgen generates lowercase type names matching the C declarations.
// These aliases let the rest of the codebase use idiomatic Rust naming.

pub type Ua = ua;
pub type Call = call;
pub type Bevent = bevent;
pub type Audio = audio;
pub type AccountC = account;
pub type Config = config;
pub type Pl = pl;
pub type List = list;
pub type Le = le;
pub type SipMsg = sip_msg;
pub type SipTaddr = sip_taddr;
pub type SipHdr = sip_hdr;
pub type Vidmode = vidmode;
pub type DtmfMode = dtmfmode;
pub type BeventEv = bevent_ev;
pub type Play = play;
