use anyhow::{Context, Result};
use crossterm::{
    execute,
    terminal::{EnterAlternateScreen, LeaveAlternateScreen, disable_raw_mode, enable_raw_mode},
};
use ratatui::{Terminal, backend::CrosstermBackend};
use serde::{Deserialize, Serialize};
use std::{fs, io, os::unix::fs::symlink, path::PathBuf};

// Embedded default baresip config — copied from ~/.baresip/config
const DEFAULT_CONFIG: &str = include_str!("../assets/default_config");

#[derive(Debug, Serialize, Deserialize, Clone, Default)]
pub struct Profile {
    pub display_name: Option<String>,
    pub username: String,
    pub auth_user: Option<String>,
    pub password: String,
    pub domain: String,
    pub transport: Option<String>,
    pub outbound: Option<String>,
    pub stun_server: Option<String>,
    pub media_enc: Option<String>,
    #[serde(default = "default_true")]
    pub notify: bool,
    #[serde(default = "default_true")]
    pub mwi: bool,
}

fn default_true() -> bool {
    true
}

impl Profile {
    /// Generate the single active line for the baresip `accounts` file.
    pub fn to_accounts_line(&self) -> String {
        let display = self
            .display_name
            .as_deref()
            .filter(|s| !s.is_empty())
            .map(|s| format!("{} ", s))
            .unwrap_or_default();

        let transport = self
            .transport
            .as_deref()
            .filter(|s| !s.is_empty())
            .map(|s| format!(";transport={}", s))
            .unwrap_or_default();

        let auth_user = self
            .auth_user
            .as_deref()
            .filter(|s| !s.is_empty())
            .unwrap_or(&self.username);

        let mut line = format!(
            "{}<sip:{}@{}{}>; auth_user={};auth_pass={}",
            display, self.username, self.domain, transport, auth_user, self.password
        );

        if let Some(v) = self.outbound.as_deref().filter(|s| !s.is_empty()) {
            line.push_str(&format!(";outbound={}", v));
        }
        if let Some(v) = self.stun_server.as_deref().filter(|s| !s.is_empty()) {
            line.push_str(&format!(";stunserver={}", v));
        }
        if let Some(v) = self.media_enc.as_deref().filter(|s| !s.is_empty()) {
            line.push_str(&format!(";mediaenc={}", v));
        }

        line
    }

    /// The SIP AOR string for this profile.
    pub fn aor(&self) -> String {
        format!("sip:{}@{}", self.username, self.domain)
    }
}

// ─── Paths ───────────────────────────────────────────────────────────────────

pub fn profiles_dir() -> Result<PathBuf> {
    let base = dirs_base()?;
    Ok(base.join("profiles"))
}

pub fn dirs_base() -> Result<PathBuf> {
    let home = std::env::var("HOME").context("HOME not set")?;
    Ok(PathBuf::from(home).join(".config").join("ringo"))
}

pub fn profile_dir(name: &str) -> Result<PathBuf> {
    Ok(profiles_dir()?.join(name))
}

// ─── List ────────────────────────────────────────────────────────────────────

pub fn list_names() -> Result<Vec<String>> {
    let dir = profiles_dir()?;
    if !dir.exists() {
        return Ok(vec![]);
    }
    let mut names: Vec<String> = fs::read_dir(&dir)?
        .filter_map(|e| e.ok())
        .filter(|e| e.path().is_dir())
        .filter(|e| e.path().join("profile.toml").exists())
        .filter_map(|e| e.file_name().into_string().ok())
        .collect();
    names.sort();
    Ok(names)
}

pub fn list(plain: bool) -> Result<()> {
    let names = list_names()?;
    if plain {
        for name in &names {
            println!("{}", name);
        }
        return Ok(());
    }
    if names.is_empty() {
        println!("No profiles found. Run: ringo");
        return Ok(());
    }
    println!("Profiles ({}):", names.len());
    for name in &names {
        let p = load(name)?;
        let transport = p.transport.as_deref().unwrap_or("default");
        println!(
            "  {:20}  {}@{}  [{}]",
            name, p.username, p.domain, transport
        );
    }
    Ok(())
}

// ─── Load / Save ─────────────────────────────────────────────────────────────

pub fn load(name: &str) -> Result<Profile> {
    let path = profile_dir(name)?.join("profile.toml");
    let raw =
        fs::read_to_string(&path).with_context(|| format!("Cannot read profile '{}'", name))?;
    toml::from_str(&raw).with_context(|| format!("Invalid profile.toml for '{}'", name))
}

pub fn save(name: &str, profile: &Profile) -> Result<()> {
    let base = dirs_base()?;
    let dir = profile_dir(name)?;
    fs::create_dir_all(&dir)?;

    // profile.toml
    let toml_str = toml::to_string_pretty(profile)?;
    fs::write(dir.join("profile.toml"), toml_str)?;

    // accounts — unique per profile, generated from metadata
    let accounts = format!(
        "# Generated by ringo — do not edit manually\n{}\n",
        profile.to_accounts_line()
    );
    fs::write(dir.join("accounts"), accounts)?;

    // config — generated from shared template with ctrl_tcp settings (port 0 = placeholder)
    let config_content = generate_config_content(profile, 0)?;
    // Remove old symlink if present
    let config_link = dir.join("config");
    if config_link.is_symlink() || config_link.exists() {
        fs::remove_file(&config_link)?;
    }
    fs::write(&config_link, config_content)?;

    // contacts — symlink to shared file
    let shared_contacts = base.join("contacts");
    if !shared_contacts.exists() {
        fs::write(&shared_contacts, "# baresip contacts\n")?;
    }
    let contacts_link = dir.join("contacts");
    if contacts_link.exists() || contacts_link.is_symlink() {
        fs::remove_file(&contacts_link)?;
    }
    symlink(&shared_contacts, &contacts_link)
        .with_context(|| "Failed to create symlink for contacts")?;

    Ok(())
}

// ─── Config generation ────────────────────────────────────────────────────────

/// Read shared template and generate a profile-specific config with ctrl_tcp settings.
/// `port` is written into `ctrl_tcp_listen`; pass 0 when generating a placeholder config.
pub fn generate_config_content(profile: &Profile, port: u16) -> Result<String> {
    let base = dirs_base()?;
    let template_path = base.join("config");

    let template = if template_path.exists() {
        fs::read_to_string(&template_path)?
    } else {
        // Bootstrap shared template from embedded default
        fs::create_dir_all(&base)?;
        fs::write(&template_path, DEFAULT_CONFIG)?;
        DEFAULT_CONFIG.to_string()
    };

    Ok(apply_ctrl_tcp_config(&template, port, profile.mwi))
}

fn apply_ctrl_tcp_config(template: &str, port: u16, mwi: bool) -> String {
    let mut lines: Vec<String> = template.lines().map(|l| l.to_string()).collect();

    // 1. Comment out modules that interfere with headless operation:
    //    - stdio.so: interactive terminal UI (replaced by our TUI)
    //    - netroam.so: delays registration until network change event fires
    const HEADLESS_DISABLE: &[&str] = &["stdio.so", "netroam.so"];
    for line in &mut lines {
        let trimmed = line.trim();
        if trimmed.starts_with('#') {
            continue; // already commented
        }
        if trimmed.starts_with("module") && HEADLESS_DISABLE.iter().any(|m| trimmed.ends_with(m)) {
            *line = format!("#{}", line);
        }
    }

    // 2. Uncomment / activate required module_app entries
    let mut modules: Vec<(&str, &str)> = vec![("ctrl_tcp.so", "module_app\t\tctrl_tcp.so")];
    if mwi {
        modules.push(("mwi.so", "module_app\t\tmwi.so"));
    }
    for (module, line_str) in &modules {
        let mut found = false;
        for line in &mut lines {
            let stripped = line.trim_start_matches('#').trim();
            if stripped.starts_with("module") && stripped.ends_with(module) {
                *line = line_str.to_string();
                found = true;
            }
        }
        if !found {
            lines.push(line_str.to_string());
        }
    }

    // 3. Set ctrl_tcp_listen to our port
    let ctrl_listen_line = format!(
        "ctrl_tcp_listen\t\t0.0.0.0:{} # ctrl_tcp - TCP interface JSON",
        port
    );
    let mut found_listen = false;
    for line in &mut lines {
        let stripped = line.trim_start_matches('#').trim();
        if stripped.starts_with("ctrl_tcp_listen") {
            *line = ctrl_listen_line.clone();
            found_listen = true;
        }
    }
    if !found_listen {
        lines.push(ctrl_listen_line);
    }

    let mut result = lines.join("\n");
    result.push('\n');
    result
}

// ─── Sync ─────────────────────────────────────────────────────────────────────

pub fn sync_all() -> Result<()> {
    let names = list_names()?;
    if names.is_empty() {
        println!("No profiles to sync.");
        return Ok(());
    }
    println!("Syncing {} profile(s)...", names.len());
    for name in &names {
        let profile = load(name)?;
        let config = generate_config_content(&profile, 0)?;
        let dir = profile_dir(name)?;
        let config_path = dir.join("config");
        if config_path.is_symlink() {
            fs::remove_file(&config_path)?;
        }
        fs::write(&config_path, config)?;
        println!("  {} — config updated", name);
    }
    Ok(())
}

// ─── Interactive profile picker (ratatui) ────────────────────────────────────

/// Open the interactive profile picker; loops until a profile is selected to start.
/// Manages the terminal lifecycle; stays in alternate screen on success so the
/// TUI can take over seamlessly.
pub fn pick_profile() -> Result<String> {
    enable_raw_mode()?;
    let mut stdout = io::stdout();
    execute!(stdout, EnterAlternateScreen)?;
    let backend = CrosstermBackend::new(stdout);
    let mut terminal = Terminal::new(backend)?;

    let result = pick_profile_loop(&mut terminal);

    if result.is_err() {
        let _ = disable_raw_mode();
        let _ = execute!(terminal.backend_mut(), LeaveAlternateScreen);
    }

    result
}

fn pick_profile_loop(terminal: &mut Terminal<CrosstermBackend<io::Stdout>>) -> Result<String> {
    use crate::picker::{PickerAction, PickerItem};
    let config = crate::config::load();
    let theme = &config.theme;
    loop {
        let names = list_names().unwrap_or_default();
        let items: Vec<PickerItem> = names
            .iter()
            .map(|name| {
                let subtitle = load(name)
                    .map(|p| build_subtitle(&p, &config.picker.info))
                    .unwrap_or_default();
                PickerItem {
                    name: name.clone(),
                    subtitle,
                }
            })
            .collect();
        match crate::picker::run(terminal, &items, theme)? {
            PickerAction::Start(name) => return Ok(name),
            PickerAction::New => {
                if let Some((name, profile)) =
                    crate::form::run_form(terminal, None, &Profile::default(), &names, theme)?
                {
                    save(&name, &profile)?;
                }
            }
            PickerAction::Edit(name) => {
                let current = load(&name)?;
                if let Some((_, profile)) =
                    crate::form::run_form(terminal, Some(&name), &current, &[], theme)?
                {
                    save(&name, &profile)?;
                }
            }
            PickerAction::Delete(name) => {
                if crate::form::run_confirm(terminal, &name, theme)? {
                    fs::remove_dir_all(profile_dir(&name)?)?;
                }
            }
        }
    }
}

fn build_subtitle(profile: &Profile, fields: &[String]) -> String {
    fields
        .iter()
        .filter_map(|f| match f.as_str() {
            "aor" => Some(profile.aor()),
            "username" => Some(profile.username.clone()),
            "domain" => Some(profile.domain.clone()),
            "display_name" => profile.display_name.clone().filter(|s| !s.is_empty()),
            "transport" => Some(
                profile
                    .transport
                    .as_deref()
                    .unwrap_or("default")
                    .to_string(),
            ),
            "auth_user" => profile.auth_user.clone().filter(|s| !s.is_empty()),
            "outbound" => profile.outbound.clone().filter(|s| !s.is_empty()),
            "stun_server" => profile.stun_server.clone().filter(|s| !s.is_empty()),
            "media_enc" => Some(profile.media_enc.as_deref().unwrap_or("none").to_string()),
            _ => None,
        })
        .filter(|s| !s.is_empty())
        .collect::<Vec<_>>()
        .join("  ·  ")
}
